set -g default-terminal "tmux-256color"

set -as terminal-overrides ',*:Tc'
set -as terminal-overrides ',*:RGB'
set -as terminal-overrides ',*:Smulx=\E[4\:%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m'

set -g mouse on
set -s set-clipboard on
set -s escape-time 10
unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode MouseDragEnd1Pane

set -g base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-x kill-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status "on"
set -g status-style "bg=#222436"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g message-style "fg=#86e1fc,bg=#3a3f5a,align=centre"

set -g window-status-activity-style "fg=#c8d3f5,bg=#222436,none"
set -g window-status-separator ""
set -g window-status-style "fg=#c8d3f5,bg=#222436,none"

set -g window-status-current-format "#[fg=#82aaff,bg=#222436] #I: #[fg=#c099ff,bg=#222436](✓) #[fg=#86e1fc,bg=#222436]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=#c099ff,bg=#222436]"
set -g window-status-format "#[fg=#82aaff,bg=#222436] #I: #[fg=#c8d3f5,bg=#222436]#W"

set -g status-right "#[fg=#82aaff,bg=#222436,nobold,nounderscore,noitalics]#[fg=#222436,bg=#82aaff,nobold,nounderscore,noitalics] #[fg=#c8d3f5,bg=#3a3f5a] #W #{?client_prefix,#[fg=#c099ff],#[fg=#86e1fc]}#[bg=#3a3f5a]#{?client_prefix,#[bg=#c099ff],#[bg=#86e1fc]}#[fg=#222436] #[fg=#c8d3f5,bg=#3a3f5a] #S "
set -g status-left ""

set -g clock-mode-colour "#82aaff"
set -g mode-style "fg=#82aaff,bg=#444a73,bold"
