name: "build & cache"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for ISO Release'
        required: false
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: victus
            attr: .#nixosConfigurations.victus.config.system.build.toplevel
            is_iso: false
          - name: iso
            attr: .#nixosConfigurations.iso.config.system.build.isoImage
            is_iso: true
    steps:
      - uses: actions/checkout@v4

      - name: free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: cachix/cachix-action@v17
        with:
          name: ar175-lol-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build ${{ matrix.target.name }}
        run: nix build "${{ matrix.target.attr }}" --fallback

      - name: upload iso (step 0)
        if: matrix.target.is_iso
        run: |
          mkdir -p output
          cp result/iso/*.iso output/nixos-installer.iso

      - name: upload iso (step 1)
        if: matrix.target.is_iso
        uses: actions/upload-artifact@v4
        with:
          name: nixos-installer-iso
          path: output/nixos-installer.iso
          retention-days: 7

      - name: upload iso (step 2)
        if: matrix.target.is_iso && github.event.inputs.tag_name != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          target_commitish: ${{ github.sha }}
          name: ${{ github.event.inputs.tag_name }}
          files: output/nixos-installer.iso
          fail_on_unmatched_files: true
